export const ADD_ARTICLE_TRIGGERED = "ADD_ARTICLE_TRIGGERED";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_SUCCEEDED = "ADD_ARTICLE_SUCCEEDED";
export const ADD_ARTICLE_FAILED = "ADD_ARTICLE_FAILED";
export const BAD_WORD_FOUND = "BAD_WORD_FOUND";
